[balance_transfer]
add_format = "ADD.{destination}.{val}.{pin}"
trans_format = "TRANS.{destination}.{val}.{pin}"

[client_config]
blocked_referrals = []

[combotrx]
outbox_like_pattern = "%{product}.{destination}%Sukses%"
sdh_pernah_filter = "%sdh pernah%"

[trx]
pesan_format_no_val = "{trxid}.{product}.{destination}.{pin}"
pesan_format_with_val_nonzero = "{trxid}.{product}.{destination}.{val}.{pin}"
pesan_format_with_val_zero = "{product}.{destination}.{pin}.{val}"
combo_code_format = "{trxid}.{combo_code}.{product}.{destination}.{pin}"

[commission_exchange]
tukar_format = "TUKAR.{val}.{pin}"

[cors_config]
allow_credentials = true
allowed_headers = [
    "Content-Type",
    "Authorization",
    "X-Requested-With",
    "Session-Key",
    "Auth-Seed",
    "X-Token",
    "Upgrade",
    "Connection",
    "Sec-WebSocket-Key",
    "Sec-WebSocket-Version",
    "Sec-WebSocket-Protocol",
]
allowed_methods = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
    "PATCH",
]
allowed_origins = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:4000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:4000",
    "http://127.0.0.1:5173",
  "http://100.114.202.107:4000",
    "https://api.hexaloom.com",
    "https://web.hexaloom.com",
    "http://10.0.2.28:4000",
]

[cutoff]
cutoff_end = "00:15"
cutoff_start = "23:45"

[demo]
number = "082233445566"

[history]
minimum_harga_to_display_in_history = 1.0

[poin]
exchange_rate = 4.0
minimum_exchange = 500.0

[server_config]
suppress_encryption_warnings = true

